name: PR

on:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-slim
    if: "!contains(github.event.pull_request.title, 'skip')"
    steps:
      - run: echo "$TITLE"
        env:
          TITLE: ${{ github.event.pull_request.title }}
